# This is a basic workflow to help you get started with Actions

name: Create Threat Model

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: windows-2022

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
#      - name: Installing .NET CORE
#        run: sudo apt-get install -y dotnet-runtime-6.0

      - name: Getting TM CLI
        run: Invoke-WebRequest -Uri "https://drive.google.com/uc?export=download&id=1OMta5N9ZjMqPfP9xOsZU0O8-GjXXmyQv" -OutFile tm_runfiles.zip
      - name: Unzip CLI
        run: Expand-Archive -LiteralPath tm_runfiles.zip -DestinationPath .\tmrunfiles

      - name: CAT CLI
        run: cat .\tmrunfiles\logins

      - name: Test CLI
        run: .\tmrunfiles\tmutil show_comp
        

